/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as CampusAdminRouteImport } from './routes/campus-admin'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DisputeRouteImport } from './routes/dispute'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as StaffInviteRouteImport } from './routes/staff-invite'
import { Route as StudentOsRouteImport } from './routes/student-os'
import { Route as SuperRouteImport } from './routes/super'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as BuyerCartRouteImport } from './routes/buyer.cart'
import { Route as BuyerCategoriesRouteImport } from './routes/buyer.categories'
import { Route as BuyerCheckoutRouteImport } from './routes/buyer.checkout'
import { Route as BuyerDealsRouteImport } from './routes/buyer.deals'
import { Route as BuyerInstallmentsRouteImport } from './routes/buyer.installments'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer.notifications'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerReserveRouteImport } from './routes/buyer.reserve'
import { Route as BuyerSearchRouteImport } from './routes/buyer.search'
import { Route as BuyerWalletRouteImport } from './routes/buyer.wallet'
import { Route as BuyerWishlistRouteImport } from './routes/buyer.wishlist'
import { Route as CampusAdminDashboardRouteImport } from './routes/campus-admin.dashboard'
import { Route as SellerIndexRouteImport } from './routes/seller.index'
import { Route as SellerIntelligenceRouteImport } from './routes/seller.intelligence'
import { Route as StudentOsIndexRouteImport } from './routes/student-os.index'
import { Route as StudentOsCalendarRouteImport } from './routes/student-os.calendar'
import { Route as StudentOsDealsRouteImport } from './routes/student-os.deals'
import { Route as StudentOsEventsRouteImport } from './routes/student-os.events'
import { Route as StudentOsLostFoundRouteImport } from './routes/student-os.lost-found'
import { Route as StudentOsMarketplaceRouteImport } from './routes/student-os.marketplace'
import { Route as StudentOsOpportunitiesRouteImport } from './routes/student-os.opportunities'
import { Route as StudentOsResourcesRouteImport } from './routes/student-os.resources'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as SuperStaffRouteImport } from './routes/super.staff'
import { Route as SuperViewAsRouteImport } from './routes/super.view-as'
import { Route as BuyerOrdersOrderIdRouteImport } from './routes/buyer.orders.$orderId'
import { Route as BuyerProductIdRouteImport } from './routes/buyer.product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusAdminRoute = CampusAdminRouteImport.update({
  id: '/campus-admin',
  path: '/campus-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputeRoute = DisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffInviteRoute = StaffInviteRouteImport.update({
  id: '/staff-invite',
  path: '/staff-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentOsRoute = StudentOsRouteImport.update({
  id: '/student-os',
  path: '/student-os',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCartRoute = BuyerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCategoriesRoute = BuyerCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCheckoutRoute = BuyerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerDealsRoute = BuyerDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerInstallmentsRoute = BuyerInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerReserveRoute = BuyerReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerSearchRoute = BuyerSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerWalletRoute = BuyerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerWishlistRoute = BuyerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => BuyerRoute,
} as any)
const CampusAdminDashboardRoute = CampusAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CampusAdminRoute,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerRoute,
} as any)
const SellerIntelligenceRoute = SellerIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => SellerRoute,
} as any)
const StudentOsIndexRoute = StudentOsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsCalendarRoute = StudentOsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsDealsRoute = StudentOsDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsEventsRoute = StudentOsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsLostFoundRoute = StudentOsLostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsMarketplaceRoute = StudentOsMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsOpportunitiesRoute = StudentOsOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => StudentOsRoute,
} as any)
const StudentOsResourcesRoute = StudentOsResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentOsRoute,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const SuperStaffRoute = SuperStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SuperRoute,
} as any)
const SuperViewAsRoute = SuperViewAsRouteImport.update({
  id: '/view-as',
  path: '/view-as',
  getParentRoute: () => SuperRoute,
} as any)
const BuyerOrdersOrderIdRoute = BuyerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => BuyerOrdersRoute,
} as any)
const BuyerProductIdRoute = BuyerProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => BuyerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/campus-admin': typeof CampusAdminRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/dispute': typeof DisputeRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/staff-invite': typeof StaffInviteRoute
  '/student-os': typeof StudentOsRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/categories': typeof BuyerCategoriesRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/deals': typeof BuyerDealsRoute
  '/buyer/installments': typeof BuyerInstallmentsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/reserve': typeof BuyerReserveRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/campus-admin/dashboard': typeof CampusAdminDashboardRoute
  '/seller/intelligence': typeof SellerIntelligenceRoute
  '/student-os/calendar': typeof StudentOsCalendarRoute
  '/student-os/deals': typeof StudentOsDealsRoute
  '/student-os/events': typeof StudentOsEventsRoute
  '/student-os/lost-found': typeof StudentOsLostFoundRoute
  '/student-os/marketplace': typeof StudentOsMarketplaceRoute
  '/student-os/opportunities': typeof StudentOsOpportunitiesRoute
  '/student-os/resources': typeof StudentOsResourcesRoute
  '/super/staff': typeof SuperStaffRoute
  '/super/view-as': typeof SuperViewAsRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/student-os/': typeof StudentOsIndexRoute
  '/super/': typeof SuperIndexRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/campus-admin': typeof CampusAdminRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/dispute': typeof DisputeRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/staff-invite': typeof StaffInviteRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/categories': typeof BuyerCategoriesRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/deals': typeof BuyerDealsRoute
  '/buyer/installments': typeof BuyerInstallmentsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/reserve': typeof BuyerReserveRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/campus-admin/dashboard': typeof CampusAdminDashboardRoute
  '/seller/intelligence': typeof SellerIntelligenceRoute
  '/student-os/calendar': typeof StudentOsCalendarRoute
  '/student-os/deals': typeof StudentOsDealsRoute
  '/student-os/events': typeof StudentOsEventsRoute
  '/student-os/lost-found': typeof StudentOsLostFoundRoute
  '/student-os/marketplace': typeof StudentOsMarketplaceRoute
  '/student-os/opportunities': typeof StudentOsOpportunitiesRoute
  '/student-os/resources': typeof StudentOsResourcesRoute
  '/super/staff': typeof SuperStaffRoute
  '/super/view-as': typeof SuperViewAsRoute
  '/buyer': typeof BuyerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/student-os': typeof StudentOsIndexRoute
  '/super': typeof SuperIndexRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/campus-admin': typeof CampusAdminRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/dispute': typeof DisputeRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/seller': typeof SellerRouteWithChildren
  '/staff-invite': typeof StaffInviteRoute
  '/student-os': typeof StudentOsRouteWithChildren
  '/super': typeof SuperRouteWithChildren
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/categories': typeof BuyerCategoriesRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/deals': typeof BuyerDealsRoute
  '/buyer/installments': typeof BuyerInstallmentsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/reserve': typeof BuyerReserveRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/campus-admin/dashboard': typeof CampusAdminDashboardRoute
  '/seller/intelligence': typeof SellerIntelligenceRoute
  '/student-os/calendar': typeof StudentOsCalendarRoute
  '/student-os/deals': typeof StudentOsDealsRoute
  '/student-os/events': typeof StudentOsEventsRoute
  '/student-os/lost-found': typeof StudentOsLostFoundRoute
  '/student-os/marketplace': typeof StudentOsMarketplaceRoute
  '/student-os/opportunities': typeof StudentOsOpportunitiesRoute
  '/student-os/resources': typeof StudentOsResourcesRoute
  '/super/staff': typeof SuperStaffRoute
  '/super/view-as': typeof SuperViewAsRoute
  '/buyer/': typeof BuyerIndexRoute
  '/seller/': typeof SellerIndexRoute
  '/student-os/': typeof StudentOsIndexRoute
  '/super/': typeof SuperIndexRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buyer'
    | '/campus-admin'
    | '/delivery'
    | '/dispute'
    | '/finance'
    | '/login'
    | '/seller'
    | '/staff-invite'
    | '/student-os'
    | '/super'
    | '/buyer/cart'
    | '/buyer/categories'
    | '/buyer/checkout'
    | '/buyer/deals'
    | '/buyer/installments'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reserve'
    | '/buyer/search'
    | '/buyer/wallet'
    | '/buyer/wishlist'
    | '/campus-admin/dashboard'
    | '/seller/intelligence'
    | '/student-os/calendar'
    | '/student-os/deals'
    | '/student-os/events'
    | '/student-os/lost-found'
    | '/student-os/marketplace'
    | '/student-os/opportunities'
    | '/student-os/resources'
    | '/super/staff'
    | '/super/view-as'
    | '/buyer/'
    | '/seller/'
    | '/student-os/'
    | '/super/'
    | '/buyer/orders/$orderId'
    | '/buyer/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/campus-admin'
    | '/delivery'
    | '/dispute'
    | '/finance'
    | '/login'
    | '/staff-invite'
    | '/buyer/cart'
    | '/buyer/categories'
    | '/buyer/checkout'
    | '/buyer/deals'
    | '/buyer/installments'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reserve'
    | '/buyer/search'
    | '/buyer/wallet'
    | '/buyer/wishlist'
    | '/campus-admin/dashboard'
    | '/seller/intelligence'
    | '/student-os/calendar'
    | '/student-os/deals'
    | '/student-os/events'
    | '/student-os/lost-found'
    | '/student-os/marketplace'
    | '/student-os/opportunities'
    | '/student-os/resources'
    | '/super/staff'
    | '/super/view-as'
    | '/buyer'
    | '/seller'
    | '/student-os'
    | '/super'
    | '/buyer/orders/$orderId'
    | '/buyer/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buyer'
    | '/campus-admin'
    | '/delivery'
    | '/dispute'
    | '/finance'
    | '/login'
    | '/seller'
    | '/staff-invite'
    | '/student-os'
    | '/super'
    | '/buyer/cart'
    | '/buyer/categories'
    | '/buyer/checkout'
    | '/buyer/deals'
    | '/buyer/installments'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reserve'
    | '/buyer/search'
    | '/buyer/wallet'
    | '/buyer/wishlist'
    | '/campus-admin/dashboard'
    | '/seller/intelligence'
    | '/student-os/calendar'
    | '/student-os/deals'
    | '/student-os/events'
    | '/student-os/lost-found'
    | '/student-os/marketplace'
    | '/student-os/opportunities'
    | '/student-os/resources'
    | '/super/staff'
    | '/super/view-as'
    | '/buyer/'
    | '/seller/'
    | '/student-os/'
    | '/super/'
    | '/buyer/orders/$orderId'
    | '/buyer/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  CampusAdminRoute: typeof CampusAdminRouteWithChildren
  DeliveryRoute: typeof DeliveryRoute
  DisputeRoute: typeof DisputeRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  SellerRoute: typeof SellerRouteWithChildren
  StaffInviteRoute: typeof StaffInviteRoute
  StudentOsRoute: typeof StudentOsRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-admin': {
      id: '/campus-admin'
      path: '/campus-admin'
      fullPath: '/campus-admin'
      preLoaderRoute: typeof CampusAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute': {
      id: '/dispute'
      path: '/dispute'
      fullPath: '/dispute'
      preLoaderRoute: typeof DisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-invite': {
      id: '/staff-invite'
      path: '/staff-invite'
      fullPath: '/staff-invite'
      preLoaderRoute: typeof StaffInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-os': {
      id: '/student-os'
      path: '/student-os'
      fullPath: '/student-os'
      preLoaderRoute: typeof StudentOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/cart': {
      id: '/buyer/cart'
      path: '/cart'
      fullPath: '/buyer/cart'
      preLoaderRoute: typeof BuyerCartRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/categories': {
      id: '/buyer/categories'
      path: '/categories'
      fullPath: '/buyer/categories'
      preLoaderRoute: typeof BuyerCategoriesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/checkout': {
      id: '/buyer/checkout'
      path: '/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof BuyerCheckoutRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/deals': {
      id: '/buyer/deals'
      path: '/deals'
      fullPath: '/buyer/deals'
      preLoaderRoute: typeof BuyerDealsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/installments': {
      id: '/buyer/installments'
      path: '/installments'
      fullPath: '/buyer/installments'
      preLoaderRoute: typeof BuyerInstallmentsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/reserve': {
      id: '/buyer/reserve'
      path: '/reserve'
      fullPath: '/buyer/reserve'
      preLoaderRoute: typeof BuyerReserveRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/search': {
      id: '/buyer/search'
      path: '/search'
      fullPath: '/buyer/search'
      preLoaderRoute: typeof BuyerSearchRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/wallet': {
      id: '/buyer/wallet'
      path: '/wallet'
      fullPath: '/buyer/wallet'
      preLoaderRoute: typeof BuyerWalletRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/wishlist': {
      id: '/buyer/wishlist'
      path: '/wishlist'
      fullPath: '/buyer/wishlist'
      preLoaderRoute: typeof BuyerWishlistRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/campus-admin/dashboard': {
      id: '/campus-admin/dashboard'
      path: '/dashboard'
      fullPath: '/campus-admin/dashboard'
      preLoaderRoute: typeof CampusAdminDashboardRouteImport
      parentRoute: typeof CampusAdminRoute
    }
    '/seller/': {
      id: '/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof SellerRoute
    }
    '/seller/intelligence': {
      id: '/seller/intelligence'
      path: '/intelligence'
      fullPath: '/seller/intelligence'
      preLoaderRoute: typeof SellerIntelligenceRouteImport
      parentRoute: typeof SellerRoute
    }
    '/student-os/': {
      id: '/student-os/'
      path: '/'
      fullPath: '/student-os/'
      preLoaderRoute: typeof StudentOsIndexRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/calendar': {
      id: '/student-os/calendar'
      path: '/calendar'
      fullPath: '/student-os/calendar'
      preLoaderRoute: typeof StudentOsCalendarRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/deals': {
      id: '/student-os/deals'
      path: '/deals'
      fullPath: '/student-os/deals'
      preLoaderRoute: typeof StudentOsDealsRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/events': {
      id: '/student-os/events'
      path: '/events'
      fullPath: '/student-os/events'
      preLoaderRoute: typeof StudentOsEventsRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/lost-found': {
      id: '/student-os/lost-found'
      path: '/lost-found'
      fullPath: '/student-os/lost-found'
      preLoaderRoute: typeof StudentOsLostFoundRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/marketplace': {
      id: '/student-os/marketplace'
      path: '/marketplace'
      fullPath: '/student-os/marketplace'
      preLoaderRoute: typeof StudentOsMarketplaceRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/opportunities': {
      id: '/student-os/opportunities'
      path: '/opportunities'
      fullPath: '/student-os/opportunities'
      preLoaderRoute: typeof StudentOsOpportunitiesRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/student-os/resources': {
      id: '/student-os/resources'
      path: '/resources'
      fullPath: '/student-os/resources'
      preLoaderRoute: typeof StudentOsResourcesRouteImport
      parentRoute: typeof StudentOsRoute
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/staff': {
      id: '/super/staff'
      path: '/staff'
      fullPath: '/super/staff'
      preLoaderRoute: typeof SuperStaffRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/view-as': {
      id: '/super/view-as'
      path: '/view-as'
      fullPath: '/super/view-as'
      preLoaderRoute: typeof SuperViewAsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/buyer/orders/$orderId': {
      id: '/buyer/orders/$orderId'
      path: '/$orderId'
      fullPath: '/buyer/orders/$orderId'
      preLoaderRoute: typeof BuyerOrdersOrderIdRouteImport
      parentRoute: typeof BuyerOrdersRoute
    }
    '/buyer/product/$id': {
      id: '/buyer/product/$id'
      path: '/product/$id'
      fullPath: '/buyer/product/$id'
      preLoaderRoute: typeof BuyerProductIdRouteImport
      parentRoute: typeof BuyerRoute
    }
  }
}

interface BuyerOrdersRouteChildren {
  BuyerOrdersOrderIdRoute: typeof BuyerOrdersOrderIdRoute
}

const BuyerOrdersRouteChildren: BuyerOrdersRouteChildren = {
  BuyerOrdersOrderIdRoute: BuyerOrdersOrderIdRoute,
}

const BuyerOrdersRouteWithChildren = BuyerOrdersRoute._addFileChildren(
  BuyerOrdersRouteChildren,
)

interface BuyerRouteChildren {
  BuyerCartRoute: typeof BuyerCartRoute
  BuyerCategoriesRoute: typeof BuyerCategoriesRoute
  BuyerCheckoutRoute: typeof BuyerCheckoutRoute
  BuyerDealsRoute: typeof BuyerDealsRoute
  BuyerInstallmentsRoute: typeof BuyerInstallmentsRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerOrdersRoute: typeof BuyerOrdersRouteWithChildren
  BuyerReserveRoute: typeof BuyerReserveRoute
  BuyerSearchRoute: typeof BuyerSearchRoute
  BuyerWalletRoute: typeof BuyerWalletRoute
  BuyerWishlistRoute: typeof BuyerWishlistRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  BuyerProductIdRoute: typeof BuyerProductIdRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerCartRoute: BuyerCartRoute,
  BuyerCategoriesRoute: BuyerCategoriesRoute,
  BuyerCheckoutRoute: BuyerCheckoutRoute,
  BuyerDealsRoute: BuyerDealsRoute,
  BuyerInstallmentsRoute: BuyerInstallmentsRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerOrdersRoute: BuyerOrdersRouteWithChildren,
  BuyerReserveRoute: BuyerReserveRoute,
  BuyerSearchRoute: BuyerSearchRoute,
  BuyerWalletRoute: BuyerWalletRoute,
  BuyerWishlistRoute: BuyerWishlistRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  BuyerProductIdRoute: BuyerProductIdRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

interface CampusAdminRouteChildren {
  CampusAdminDashboardRoute: typeof CampusAdminDashboardRoute
}

const CampusAdminRouteChildren: CampusAdminRouteChildren = {
  CampusAdminDashboardRoute: CampusAdminDashboardRoute,
}

const CampusAdminRouteWithChildren = CampusAdminRoute._addFileChildren(
  CampusAdminRouteChildren,
)

interface SellerRouteChildren {
  SellerIntelligenceRoute: typeof SellerIntelligenceRoute
  SellerIndexRoute: typeof SellerIndexRoute
}

const SellerRouteChildren: SellerRouteChildren = {
  SellerIntelligenceRoute: SellerIntelligenceRoute,
  SellerIndexRoute: SellerIndexRoute,
}

const SellerRouteWithChildren =
  SellerRoute._addFileChildren(SellerRouteChildren)

interface StudentOsRouteChildren {
  StudentOsCalendarRoute: typeof StudentOsCalendarRoute
  StudentOsDealsRoute: typeof StudentOsDealsRoute
  StudentOsEventsRoute: typeof StudentOsEventsRoute
  StudentOsLostFoundRoute: typeof StudentOsLostFoundRoute
  StudentOsMarketplaceRoute: typeof StudentOsMarketplaceRoute
  StudentOsOpportunitiesRoute: typeof StudentOsOpportunitiesRoute
  StudentOsResourcesRoute: typeof StudentOsResourcesRoute
  StudentOsIndexRoute: typeof StudentOsIndexRoute
}

const StudentOsRouteChildren: StudentOsRouteChildren = {
  StudentOsCalendarRoute: StudentOsCalendarRoute,
  StudentOsDealsRoute: StudentOsDealsRoute,
  StudentOsEventsRoute: StudentOsEventsRoute,
  StudentOsLostFoundRoute: StudentOsLostFoundRoute,
  StudentOsMarketplaceRoute: StudentOsMarketplaceRoute,
  StudentOsOpportunitiesRoute: StudentOsOpportunitiesRoute,
  StudentOsResourcesRoute: StudentOsResourcesRoute,
  StudentOsIndexRoute: StudentOsIndexRoute,
}

const StudentOsRouteWithChildren = StudentOsRoute._addFileChildren(
  StudentOsRouteChildren,
)

interface SuperRouteChildren {
  SuperStaffRoute: typeof SuperStaffRoute
  SuperViewAsRoute: typeof SuperViewAsRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperStaffRoute: SuperStaffRoute,
  SuperViewAsRoute: SuperViewAsRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuyerRoute: BuyerRouteWithChildren,
  CampusAdminRoute: CampusAdminRouteWithChildren,
  DeliveryRoute: DeliveryRoute,
  DisputeRoute: DisputeRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  SellerRoute: SellerRouteWithChildren,
  StaffInviteRoute: StaffInviteRoute,
  StudentOsRoute: StudentOsRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
