/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BuyerRouteImport } from './routes/buyer'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DisputeRouteImport } from './routes/dispute'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SuperRouteImport } from './routes/super'
import { Route as BuyerIndexRouteImport } from './routes/buyer.index'
import { Route as BuyerCartRouteImport } from './routes/buyer.cart'
import { Route as BuyerCheckoutRouteImport } from './routes/buyer.checkout'
import { Route as BuyerInstallmentsRouteImport } from './routes/buyer.installments'
import { Route as BuyerMessagesRouteImport } from './routes/buyer.messages'
import { Route as BuyerNotificationsRouteImport } from './routes/buyer.notifications'
import { Route as BuyerOrdersRouteImport } from './routes/buyer.orders'
import { Route as BuyerReserveRouteImport } from './routes/buyer.reserve'
import { Route as BuyerSearchRouteImport } from './routes/buyer.search'
import { Route as BuyerWalletRouteImport } from './routes/buyer.wallet'
import { Route as BuyerWishlistRouteImport } from './routes/buyer.wishlist'
import { Route as BuyerOrdersOrderIdRouteImport } from './routes/buyer.orders.$orderId'
import { Route as BuyerProductIdRouteImport } from './routes/buyer.product.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRoute = BuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputeRoute = DisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCartRoute = BuyerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerCheckoutRoute = BuyerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerInstallmentsRoute = BuyerInstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerMessagesRoute = BuyerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerNotificationsRoute = BuyerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersRoute = BuyerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerReserveRoute = BuyerReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerSearchRoute = BuyerSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerWalletRoute = BuyerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerWishlistRoute = BuyerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => BuyerRoute,
} as any)
const BuyerOrdersOrderIdRoute = BuyerOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => BuyerOrdersRoute,
} as any)
const BuyerProductIdRoute = BuyerProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => BuyerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/dispute': typeof DisputeRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/seller': typeof SellerRoute
  '/super': typeof SuperRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/installments': typeof BuyerInstallmentsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/reserve': typeof BuyerReserveRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/buyer/': typeof BuyerIndexRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/delivery': typeof DeliveryRoute
  '/dispute': typeof DisputeRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/seller': typeof SellerRoute
  '/super': typeof SuperRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/installments': typeof BuyerInstallmentsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/reserve': typeof BuyerReserveRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/buyer': typeof BuyerIndexRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/buyer': typeof BuyerRouteWithChildren
  '/delivery': typeof DeliveryRoute
  '/dispute': typeof DisputeRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/seller': typeof SellerRoute
  '/super': typeof SuperRoute
  '/buyer/cart': typeof BuyerCartRoute
  '/buyer/checkout': typeof BuyerCheckoutRoute
  '/buyer/installments': typeof BuyerInstallmentsRoute
  '/buyer/messages': typeof BuyerMessagesRoute
  '/buyer/notifications': typeof BuyerNotificationsRoute
  '/buyer/orders': typeof BuyerOrdersRouteWithChildren
  '/buyer/reserve': typeof BuyerReserveRoute
  '/buyer/search': typeof BuyerSearchRoute
  '/buyer/wallet': typeof BuyerWalletRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/buyer/': typeof BuyerIndexRoute
  '/buyer/orders/$orderId': typeof BuyerOrdersOrderIdRoute
  '/buyer/product/$id': typeof BuyerProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buyer'
    | '/delivery'
    | '/dispute'
    | '/finance'
    | '/login'
    | '/seller'
    | '/super'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/installments'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reserve'
    | '/buyer/search'
    | '/buyer/wallet'
    | '/buyer/wishlist'
    | '/buyer/'
    | '/buyer/orders/$orderId'
    | '/buyer/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/delivery'
    | '/dispute'
    | '/finance'
    | '/login'
    | '/seller'
    | '/super'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/installments'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reserve'
    | '/buyer/search'
    | '/buyer/wallet'
    | '/buyer/wishlist'
    | '/buyer'
    | '/buyer/orders/$orderId'
    | '/buyer/product/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buyer'
    | '/delivery'
    | '/dispute'
    | '/finance'
    | '/login'
    | '/seller'
    | '/super'
    | '/buyer/cart'
    | '/buyer/checkout'
    | '/buyer/installments'
    | '/buyer/messages'
    | '/buyer/notifications'
    | '/buyer/orders'
    | '/buyer/reserve'
    | '/buyer/search'
    | '/buyer/wallet'
    | '/buyer/wishlist'
    | '/buyer/'
    | '/buyer/orders/$orderId'
    | '/buyer/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BuyerRoute: typeof BuyerRouteWithChildren
  DeliveryRoute: typeof DeliveryRoute
  DisputeRoute: typeof DisputeRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  SellerRoute: typeof SellerRoute
  SuperRoute: typeof SuperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer': {
      id: '/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispute': {
      id: '/dispute'
      path: '/dispute'
      fullPath: '/dispute'
      preLoaderRoute: typeof DisputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/'
      fullPath: '/buyer/'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/cart': {
      id: '/buyer/cart'
      path: '/cart'
      fullPath: '/buyer/cart'
      preLoaderRoute: typeof BuyerCartRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/checkout': {
      id: '/buyer/checkout'
      path: '/checkout'
      fullPath: '/buyer/checkout'
      preLoaderRoute: typeof BuyerCheckoutRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/installments': {
      id: '/buyer/installments'
      path: '/installments'
      fullPath: '/buyer/installments'
      preLoaderRoute: typeof BuyerInstallmentsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/messages': {
      id: '/buyer/messages'
      path: '/messages'
      fullPath: '/buyer/messages'
      preLoaderRoute: typeof BuyerMessagesRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/notifications': {
      id: '/buyer/notifications'
      path: '/notifications'
      fullPath: '/buyer/notifications'
      preLoaderRoute: typeof BuyerNotificationsRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders': {
      id: '/buyer/orders'
      path: '/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof BuyerOrdersRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/reserve': {
      id: '/buyer/reserve'
      path: '/reserve'
      fullPath: '/buyer/reserve'
      preLoaderRoute: typeof BuyerReserveRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/search': {
      id: '/buyer/search'
      path: '/search'
      fullPath: '/buyer/search'
      preLoaderRoute: typeof BuyerSearchRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/wallet': {
      id: '/buyer/wallet'
      path: '/wallet'
      fullPath: '/buyer/wallet'
      preLoaderRoute: typeof BuyerWalletRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/wishlist': {
      id: '/buyer/wishlist'
      path: '/wishlist'
      fullPath: '/buyer/wishlist'
      preLoaderRoute: typeof BuyerWishlistRouteImport
      parentRoute: typeof BuyerRoute
    }
    '/buyer/orders/$orderId': {
      id: '/buyer/orders/$orderId'
      path: '/$orderId'
      fullPath: '/buyer/orders/$orderId'
      preLoaderRoute: typeof BuyerOrdersOrderIdRouteImport
      parentRoute: typeof BuyerOrdersRoute
    }
    '/buyer/product/$id': {
      id: '/buyer/product/$id'
      path: '/product/$id'
      fullPath: '/buyer/product/$id'
      preLoaderRoute: typeof BuyerProductIdRouteImport
      parentRoute: typeof BuyerRoute
    }
  }
}

interface BuyerOrdersRouteChildren {
  BuyerOrdersOrderIdRoute: typeof BuyerOrdersOrderIdRoute
}

const BuyerOrdersRouteChildren: BuyerOrdersRouteChildren = {
  BuyerOrdersOrderIdRoute: BuyerOrdersOrderIdRoute,
}

const BuyerOrdersRouteWithChildren = BuyerOrdersRoute._addFileChildren(
  BuyerOrdersRouteChildren,
)

interface BuyerRouteChildren {
  BuyerCartRoute: typeof BuyerCartRoute
  BuyerCheckoutRoute: typeof BuyerCheckoutRoute
  BuyerInstallmentsRoute: typeof BuyerInstallmentsRoute
  BuyerMessagesRoute: typeof BuyerMessagesRoute
  BuyerNotificationsRoute: typeof BuyerNotificationsRoute
  BuyerOrdersRoute: typeof BuyerOrdersRouteWithChildren
  BuyerReserveRoute: typeof BuyerReserveRoute
  BuyerSearchRoute: typeof BuyerSearchRoute
  BuyerWalletRoute: typeof BuyerWalletRoute
  BuyerWishlistRoute: typeof BuyerWishlistRoute
  BuyerIndexRoute: typeof BuyerIndexRoute
  BuyerProductIdRoute: typeof BuyerProductIdRoute
}

const BuyerRouteChildren: BuyerRouteChildren = {
  BuyerCartRoute: BuyerCartRoute,
  BuyerCheckoutRoute: BuyerCheckoutRoute,
  BuyerInstallmentsRoute: BuyerInstallmentsRoute,
  BuyerMessagesRoute: BuyerMessagesRoute,
  BuyerNotificationsRoute: BuyerNotificationsRoute,
  BuyerOrdersRoute: BuyerOrdersRouteWithChildren,
  BuyerReserveRoute: BuyerReserveRoute,
  BuyerSearchRoute: BuyerSearchRoute,
  BuyerWalletRoute: BuyerWalletRoute,
  BuyerWishlistRoute: BuyerWishlistRoute,
  BuyerIndexRoute: BuyerIndexRoute,
  BuyerProductIdRoute: BuyerProductIdRoute,
}

const BuyerRouteWithChildren = BuyerRoute._addFileChildren(BuyerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BuyerRoute: BuyerRouteWithChildren,
  DeliveryRoute: DeliveryRoute,
  DisputeRoute: DisputeRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  SellerRoute: SellerRoute,
  SuperRoute: SuperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
